name: Generate snake animation

on:
  schedule: # Execute every 12 hours
    - cron: "0 */12 * * *" # Run at 12-hour intervals

  workflow_dispatch: # Allow manual trigger of the workflow

  push:
    branches:
      - master # Trigger on push to the master branch

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Generate the snake.svg file with github-dark theme (or github-light)
      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: anukalp-mishra
          outputs: dist/snake.svg?palette=github-dark

      # Step 3: Push snake.svg to the output branch
      - name: Push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output # Branch for the snake.svg
          build_dir: dist # Directory containing the snake.svg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
